name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: install deps
        run: npm ci --ignore-scripts
      - name: build
        run: npm run build
      - name: test
        run: npm test
    env:
      FINDY_CTS_RETRY_TIMEOUT_SECS: 1
  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: install deps
        run: npm ci --ignore-scripts
      - name: run check
        run: npm run licenses:check
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: install deps
        run: npm ci --ignore-scripts
      - name: test
        run: npm run e2e
